### ISSUE TITLE
Dialog buttons labels are missing

### ISSUE THREAD

**Issue by mtzoumas** [fieryprophet/jQuery-UI-Dialog-MinMax#1]
The buttons labels don't appear in the dialog. 
![Buttons](https://f.cloud.github.com/assets/1002316/118106/0497f860-6c65-11e2-8c84-087b15108c10.png)

**Comment by fieryprophet** [comment]
It's a problem with the older version of jQuery UI this uses, and the new jQuery. Add this to the end of your jquery-dialog.js file:

if ( $.attrFn ) { $.attrFn.text = true; }

**Comment by mtzoumas** [comment]
Thanks for your help. I did a change to the _createButtons function of the component and now when a button is created I am using the html(props.text) to update the text and now it works like a charm.
