### ISSUE TITLE
"position" does not understand an array which contains an x, y coordinate pair in pixel

### ISSUE THREAD

**Issue by ghost** [fieryprophet/jQuery-UI-Dialog-MinMax#2]

**Comment by fieryprophet** [comment]
Position has to be set via the dialog widget option mechanism, like so:

$("#dialog").dialog("option", "position", [30, 30]);

**Comment by ghost** [comment]
Yes, I do it, but when the dialog is loaded, current position [0,0], and I think it only understands "String": "center", "left", "right" ...

**Comment by fieryprophet** [comment]
Do you have an example I could look at? Setting position by array is working for me.

**Comment by ghost** [comment]
Thank you for your help, I changed file jquery.ui.dialog.minmax.js of you, line 714 -> 718, it is replaced:
position = {
                        my: myAt[0] + (offset[0] < 0 ? offset[0] : "+" + offset[0]) + " " +
                            myAt[1] + (offset[1] < 0 ? offset[1] : "+" + offset[1]),
                        at: myAt.join(" ")
                    };
//Now, it's OK ^^
